feat : Cautions-when-making-API-calls_양하연
Kernel360/blog pull request #64
Opened 2024-07-28 14:40 UTC by godhyzzang

2024-07-29 06:43 UTC, soaple reviewed
하연님께서 선정하신 주제가 기술 블로그로 작성하기에는 적합하지 않은 느낌이 듭니다.
API 호출과 관련해서 직접 겪으셨던 CORS 같은 내용을 조금 더 추가하시면 어떨까 싶습니다.
그리고 전체적으로 문장을 다른 사람에게 지식을 전달하는 형태로 바꿔보시면 좋을 것 같습니다!

2024-08-16 03:55 UTC, kciter commented
안녕하세요. 하연님.
작성하신 글 초안을 읽어보았습니다.

다른 사람들의 흥미를 끌기에 해당 주제는 조금 임팩트가 약한 것 같습니다. 아니면 글의 주제를 살짝 비틀어 `삽질을 하는 과정, 다음엔 어떻게 하면 좋겠다`와 같은 과정을 그려보면 어떨까요? 애매하다면 평소에 고민했던 지점, 혹은 공부해보고 싶었던 주제를 떠올려도 좋을 것 같습니다.

목차를 잡는게 어렵다면 먼저 이야기의 [로그라인](https://brunch.co.kr/@kyg00327/29)을 잡아보시면 좋습니다. 예를 들면 `API 호출 성공을 위한 삽질기`로 로그라인을 잡는다면 API 호출은 글의 서두일 뿐이고 **어떤 삽질을 했는가?**가 글의 내용이 될 수 있습니다.

추가로 github와 같은 고유명사는 GitHub와 같이 대소문자를 지켜주시면 좋습니다. 또한 api도 줄임말이니 API로 쓰시면 좋습니다.

2024-08-18 08:21 UTC, godhyzzang commented
부족한 글 읽어주셔서 감사합니다. 로그라인 잡아서 다음에는 조금 더 정성스레 작성해보도록 하겠습니다. 감사합니다!

2024-09-06 07:00 UTC, chan99k requested changes

2024-09-06 07:00 UTC, chan99k commented on _posts/2024-07-28-Cautions-when-making-API-calls.md
> +
백틱 ` 이 포함되어 있으면 서식을 읽지 못합니다-!! 수정 부탁드려요

2024-09-06 07:00 UTC, chan99k commented on _posts/2024-07-28-Cautions-when-making-API-calls.md
> +  image: `썸네일로 넣고 싶은 이미지 링크`
추가하고 싶으신 이미지가 따로 없으시다면 assets/images/post/2023-11-05.webp 를 작성해 주세요.

2024-09-10 03:24 UTC, chan99k approved these changes
감사합니다. 고생하셨어요-!

2024-09-10 03:24 UTC, merged