feat: 20240728_Suspense with data fetch_김승태
Kernel360/blog pull request #66
Opened 2024-07-28 17:43 UTC by dmdgpdi

2024-07-29 06:38 UTC, soaple reviewed
설명을 전개해나가는 순서를 다시 한 번 정리해보면 좋을 것 같습니다!

2024-07-29 06:38 UTC, soaple commented on _posts/2024-07-28-suspenseWithDataFetch-김승태.md
> +# Suspense with data fetching
제목을 "Suspense를 사용하여 Data Fetching 처리하기" 같은 식으로 해보면 어떨까요?

2024-07-29 06:38 UTC, soaple commented on _posts/2024-07-28-suspenseWithDataFetch-김승태.md
> +- [`lazy`](https://react.dev/reference/react/lazy) 와 함께 Lazy-loading component를 사용할 때: React.lazy와 함께 쓴다면 동적으로 컴포넌트를 가져올 때, 자연스럽게 로딩 처리를 해줄 수 있습니다.
각 케이스에 대해서 조금 더 부가적인 설명을 덧붙여주면 읽는 사람들이 이해하기 쉬울 것 같습니다!

2024-07-29 06:38 UTC, soaple commented on _posts/2024-07-28-suspenseWithDataFetch-김승태.md
> +}
코드 들여쓰기를 맞춰주시면 좋을 것 같습니다~

2024-07-29 06:38 UTC, soaple commented on _posts/2024-07-28-suspenseWithDataFetch-김승태.md
> +}
코드 들여쓰기를 맞춰주시면 좋을 것 같습니다~

2024-07-29 06:38 UTC, soaple commented on _posts/2024-07-28-suspenseWithDataFetch-김승태.md
> +const { data, isLoding } = useGetFetch(url);
오타가 있습니다~
`isLoding` => `isLoading`

2024-07-29 06:38 UTC, soaple commented on _posts/2024-07-28-suspenseWithDataFetch-김승태.md
> +이번 프로젝트는 오픈 API를 이용했기 때문에 화면에 맞는 API호출이 아닌, 연쇄적인 API호출(유저 정보 조회 → 유저 매치 목록 조회 → 유저 매치 정보 조회)을 해야했고, 코드의 복잡함을 줄이기 위해서 적용했습니다.
'이번 프로젝트'라는 것에 대한 설명이 따로 없기 때문에, 이 글만을 읽는 독자분들이 이해하기에 어려울 수 있을 것 같습니다.

2024-08-16 11:29 UTC, tonyfromundefined requested changes
수고하셨습니다! 전반적으로 많은 수정이 필요하다고 느낍니다. 실제 용례가 포함되면 좋겠는데, React Router DOM의 loader 인터페이스와 함께 use 훅 통합을 시도해보면 좋겠습니다.

use 훅: https://github.com/daangn/stackflow/blob/main/integrations/react/src/future/loader/use.ts

2024-08-16 11:29 UTC, tonyfromundefined commented on _posts/2024-07-28-suspenseWithDataFetch-김승태.md
> +  }
이건 서버 컴포넌트의 기능이지 Suspense의 기능이라고 볼 수 없습니다. 아래와 같이 표현해야합니다.

```suggestion
  function PostFeed(){
  	const feedData = usePostFeedData(); // something asynchronous action

  	return { feedData }; // return value
  }
```

2024-08-16 11:29 UTC, tonyfromundefined commented on _posts/2024-07-28-suspenseWithDataFetch-김승태.md
> +- Data fetching with Suspense-enabled한 프레임워크와 같이 사용할 때(Data fetching with Suspense-enabled frameworks like [Relay](https://relay.dev/docs/guided-tour/rendering/loading-states/) and [Next.js](https://
```suggestion
- Data fetching with Suspense-enabled한 프레임워크와 같이 사용할 때(Data fetching with Suspense-enabled frameworks like [Relay](https://relay.dev/docs/guided-tour/rendering/loading-states/)
```

Suspense는 React의 기능이지 Next.js의 기능이 아닙니다.

2024-08-16 11:29 UTC, tonyfromundefined commented on _posts/2024-07-28-suspenseWithDataFetch-김승태.md
> +  }
```suggestion
  function ChildComponent(){
  	const value = use(resource);

  	return <div>{value}</div>
  }
```

2024-08-16 11:29 UTC, tonyfromundefined commented on _posts/2024-07-28-suspenseWithDataFetch-김승태.md
> +const { data, isLoding } = useGetFetch(url);
```suggestion

## 기존 방식 (as-is)
Suspense를 사용하지 않고, React의 상태(`useState`)를 이용해 가져온 서버 데이터를 상태에 포함해 UI에 표현할 수 있습니다.

```tsx
const { data, isLoding } = useGetFetch(url);
```

2024-08-16 11:29 UTC, tonyfromundefined commented on _posts/2024-07-28-suspenseWithDataFetch-김승태.md
> +function ChildComponent(){
```suggestion

## 개선된 방식 (to-be)
Suspense를 사용하면, 특별한 비동기 처리 없이도, 외부 데이터의 의존성을 가볍게 표현할 수 있으며, ErrorBoundary와 Suspense를 통해 선언적으로 에러와 로딩 상태를 표현할 수 있습니다.

```tsx
function ChildComponent(){
```

2024-08-16 11:29 UTC, tonyfromundefined commented on _posts/2024-07-28-suspenseWithDataFetch-김승태.md
> +```
Suspense는 이렇게 Naive하게 동작하지 않습니다. React Concurrent Rendering의 의미를 심하게 곡해하기 때문에 이 섹션은 빼는 것이 좋겠습니다.

2024-08-16 11:29 UTC, tonyfromundefined commented on _posts/2024-07-28-suspenseWithDataFetch-김승태.md
> +```
React의 Concurrent Rendering은 차라리 Operating System의 Scheduler 구현과 비슷하다고 보면 좋습니다. `throw Promise` 케이스에서 인지적인 로딩 속도를 고려해 다음 렌더링을 스케쥴링합니다. (while true 하지 않습니다)

2024-08-16 11:29 UTC, tonyfromundefined commented on _posts/2024-07-28-suspenseWithDataFetch-김승태.md
> +```
이해를 돕고 싶다면, 코드로 설명하기 보다는 Diagram을 그려보면 어떨까요?

2024-08-16 11:29 UTC, tonyfromundefined commented on _posts/2024-07-28-suspenseWithDataFetch-김승태.md
> +const { data, isLoding } = useGetFetch(url);
아래에 한꺼번에 설명하기보다는 as-is와 to-be를 명시적으로 드러내면서 해당 섹션에 부연설명을 하는 것이 더 이해를 도울 것 같습니다.

2024-08-16 11:30 UTC, tonyfromundefined commented
useState + useEffect보다 Suspense 방식에서 성능 개선 포인트가 있습니다. 왜인지 생각해보시고 그 부분도 추가해보면 좋을 것 같습니다~

2024-08-16 11:32 UTC, tonyfromundefined commented on _posts/2024-07-28-suspenseWithDataFetch-김승태.md
> +# Suspense with data fetching
Data Fetching with Suspense가 아닐지...

2024-09-06 07:02 UTC, chan99k approved these changes
요청 확인하시고 변경을 부탁드립니다.

2024-09-06 07:02 UTC, chan99k commented on _posts/2024-07-28-suspenseWithDataFetch-김승태.md
> +---
백틱 ` 이 포함되어 있으면 서식이 적용되지 않습니다!! 변경 부탁드려요

![image](https://github.com/user-attachments/assets/f63f1483-e137-42ac-9f7b-2627081be0b9)

2024-09-06 08:59 UTC, chan99k approved these changes
고생하셨습니다~!! 🥇

2024-09-06 09:00 UTC, merged