feat: 20240729_JS_모듈번들러_윤예진
Kernel360/blog pull request #67
Opened 2024-07-29 00:43 UTC by Yejin0O0

2024-07-29 06:30 UTC, soaple reviewed
조금 더 기술 블로그에 맞는 톤으로 문장을 수정해보면 좋을 것 같습니다.

예를 들면 제목을 "JavaScript 모듈 번들러의 정의와 역할" 같은 형태로 수정해볼 수 있겠네요~

2024-08-16 11:17 UTC, tonyfromundefined requested changes
고생하셨습니다~

2024-08-16 11:17 UTC, tonyfromundefined commented on _posts/2024-07-29-js-module-bundler.md
> +이후 JavaScript 언어 자체에서 모듈 시스템을 지원하기 위해 ECMAScript 6에서 ES Module이라는 표준 모듈 시스템이 도입되었습니다. 이 방식은 우리가 개발할 때 흔히 사용하는 import/export 구문을 사용합니다. ES Module은 브라우저에서 지원되며, 덕분에 `<script type="module">`을 사용하여 모듈을 불
ES Module의 최소 지원 브라우저 버전을 함께 명시해두어도 좋을거같네요 ㅎㅎ Vite를 쓰는 경우 ES Module을 지원하지 않는 브라우저 대응을 위해 legacy plugin 이라는 걸 제공해요.

https://www.npmjs.com/package/@vitejs/plugin-legacy

2024-08-16 11:17 UTC, tonyfromundefined commented on _posts/2024-07-29-js-module-bundler.md
> +    번들러를 사용하지 않을 때는 각각의 JS 파일을 사용하기 위해 파일의 종속성을 고려하여 많은 스크립트 태그를 추가해야 했는데, 번들러는 파일끼리의 종속성을 알아서 확인하여 묶어줍니다.
문장이 어색하여 요렇게 수정 제안드려요.

```suggestion
    번들러를 사용하지 않을 때는 로직을 작성하기 위해 각 JS 구문들의 의존성을 개발자가 알아서 파악해야했다면, 번들러는 파일끼리의 의존성을 알아서 확인하여 묶어주기 때문에, 의존성 관리 측면에서 유지보수성이 좋아집니다.
```

2024-08-16 11:17 UTC, tonyfromundefined commented on _posts/2024-07-29-js-module-bundler.md
> +    코드가 변경되면 감지하고 브라우저에 최신 코드를 반영하여 자동으로 모듈을 교체합니다. 개발자는 새로고침을 하지 않아도 반영된 것을 빠르게 확인할 수 있으며 변경 사항만 업데이트하기 때문에 개발 속도가 빨라집니다.
"개발 속도가 빨라집니다"라는 표현은 너무 모호한거같아요. 명확하게 표현하려는 연습을 해보면 좋겠어요!

```suggestion
-   **HMR (Hot Module Replacement)**
    개발자 모드에서 코드가 변경되면 감지하고 브라우저에 최신 코드를 반영하여 자동으로 모듈을 교체합니다. 개발자는 손으로 새로고침을 하지 않아도 반영된 것을 빠르게 확인할 수 있으며 변경 사항만 업데이트하기 때문에 개발과 테스트 사이의 Iteration이 빨라집니다.
```

2024-08-16 11:17 UTC, tonyfromundefined commented on _posts/2024-07-29-js-module-bundler.md
> +    모듈 번들러가 의존성 있는 모듈끼리 번들링해서 클라이언트에게 보내 HTTP request 통신 횟수를 최소화 하여 유저의 로딩 시간을 줄였습니다. 그런데 이렇게 되면 하나의 번들 파일의 크기가 너무 커지지 않을까요? 큰 번들을 브라우저에서 파싱하고 컴파일 해야 하니 로딩 시간이 더 길어지지 않을까요? 맞습니다!
컴파일이 아니라 Evalution으로 표현하는 것이 좀 더 맞을거 같습니다 ㅎ 추가로 갑작스런 의문형 문장이 좀 당황스럽긴한거같아요.

```suggestion
    모듈 번들러가 의존성 있는 모듈끼리 번들링해서 클라이언트에게 보내 HTTP request 통신 횟수를 최소화 하여 유저의 로딩 시간을 줄였습니다. 그런데 이렇게 되면 하나의 번들 파일의 크기가 너무 커지지 않을까요? 큰 번들을 브라우저에서 파싱하고 Evaluation 해야 하니 로딩 시간이 더 길어지지 않을까요? 맞습니다!
```

2024-08-16 11:17 UTC, tonyfromundefined commented on _posts/2024-07-29-js-module-bundler.md
> +    트랜스파일러를 사용하여 ES6 버전 이상의 스크립트를 사용 가능하게 해줍니다.
Transpiling은 엄밀하게는 모듈 번들러의 역할이라고 볼 수 없으므로 삭제하는 것이 맞을거같아요. Transpiling은 Babel, TSC, SWC 등 별개로 분리된 개념으로 생각하시는게 맞아요. 번들러는 이 도구들의 통합을 도와주는 플랫폼 역할을 하구요.

2024-08-16 11:17 UTC, tonyfromundefined commented on _posts/2024-07-29-js-module-bundler.md
> +    -   코드 변경 시 브라우저를 새로 고침하지 않고도 변경 사항을 즉시 반영할 수 있는 기능을 제공합니다. 이를 통해 개발 생산성이 크게 향상됩니다.
```suggestion
    -   코드 변경 시 브라우저를 새로 고침하지 않고도 변경 사항을 즉시 반영할 수 있는 기능을 제공합니다.
```

요 섹션은 도구간의 비교여서, 특정 Feature가 주는 효용을 설명하는 것은 주제와 어긋난 것 같아요

2024-08-18 08:37 UTC, Yejin0O0 commented on _posts/2024-07-29-js-module-bundler.md
> +    -   코드 변경 시 브라우저를 새로 고침하지 않고도 변경 사항을 즉시 반영할 수 있는 기능을 제공합니다. 이를 통해 개발 생산성이 크게 향상됩니다.
피드백 감사합니다!! 반영하여 글 수정하겠습니다!😊

2024-09-04 02:57 UTC, inje-hottestlab approved these changes
커멘트 남긴 부분만 확인해서 보충해주시면 좋을 것 같습니다!

2024-09-04 02:57 UTC, inje-hottestlab commented on _posts/2024-07-29-js-module-bundler.md
> +ES Module의 최소 지원 브라우저 버전은 Chrome 61, Firefox 60, Safari 10.1, Edge 16입니다. Vite와 같은 최신 빌드 도구를 사용할 때는 ES Module을 지원하지 않는 브라우저에 대한 대응도 고려해야 합니다. Vite는 이를 위해 @vitejs/plugin-legacy라는 플러그인을 제공합니다. 이 플러그인을
여기에 각 모듈 로더 시스템 별로 예시 코드를 넣어주면 더 좋을 것 같습니다~

2024-09-04 03:02 UTC, Yejin0O0 commented on _posts/2024-07-29-js-module-bundler.md
> +ES Module의 최소 지원 브라우저 버전은 Chrome 61, Firefox 60, Safari 10.1, Edge 16입니다. Vite와 같은 최신 빌드 도구를 사용할 때는 ES Module을 지원하지 않는 브라우저에 대한 대응도 고려해야 합니다. Vite는 이를 위해 @vitejs/plugin-legacy라는 플러그인을 제공합니다. 이 플러그인을
감사합니다!

2024-09-04 03:21 UTC, merged