feat : 20240814_정적 팩토리 메서드 패턴_김택준
Kernel360/blog pull request #71
Opened 2024-08-20 01:55 UTC by xorwns118

2024-08-20 06:47 UTC, chan99k commented on 기술세미나/_posts/2024-08-14-StaticFactoryMethod.md
> +
예시 코드 블럭 등을 추가하셔서 내용 보충을 요청 드려도 될까요?

2024-08-20 06:53 UTC, chan99k requested changes
분량이 조금 짧을 것 같아서, 예시 코드 혹은 이미지 보충을 부탁드립니다-!!

2024-08-20 06:53 UTC, chan99k commented on 기술세미나/_posts/2024-08-14-StaticFactoryMethod.md
> +
여기에도 적절한 메서드 네이밍 / 부적절한 메서드 네이밍 에 대한 예시 코드 블럭이 있으면 좋을 것 같습니다

2024-08-20 06:53 UTC, chan99k commented on 기술세미나/_posts/2024-08-14-StaticFactoryMethod.md
> +
이 부분드 예시 코드 블럭 보충을 부탁드립니다.

2024-08-20 06:53 UTC, chan99k commented on 기술세미나/_posts/2024-08-14-StaticFactoryMethod.md
> +
간접적으로 호출되는 구조 이미지가 있으면 좋을 것 같습니다.
chatGPT + Mermaid 등을 잘 사용하시면 3분만에 구성하실 수 있어요.
(ChatGPT 에게 이러 이러한 구성으로 mermaid 스크립트를 만들어줘 라고 하신 다음, 해당 스크립트에서 나온 이미지를 사용하시면 됩니다!! / 기타 사용 가능한 이미지를 타 블로그 등에서 캡쳐하여 사용하셔도 무방합니다)

2024-08-20 06:53 UTC, chan99k commented on 기술세미나/_posts/2024-08-14-StaticFactoryMethod.md
> +
상속을 이용한 확장이 왜 불가능한지 예시 이미지 혹은 예시 코드 블럭이 있으면 좋을 것 같아요

2024-08-22 12:19 UTC, xorwns118 commented
수정 후 지금 브랜치에 커밋했습니다. 확인해주세요!

2024-08-27 06:47 UTC, merged