feat : 20240816_Optional_송해덕
Kernel360/blog pull request #77
Opened 2024-09-02 09:08 UTC by ss0ngcode

2024-09-05 02:03 UTC, chan99k requested changes
수정 부탁드립니다.

2024-09-05 02:03 UTC, chan99k commented on 기술세미나/_posts/2024-08-16-Optional.md
> +---
![image](https://github.com/user-attachments/assets/7f17a06e-1ced-48e3-9505-21cc3893dcde)

` 백틱을 사용하시면 인식을 못합니다...! 수정 부탁드려요

2024-09-05 05:14 UTC, ss0ngcode commented on 기술세미나/_posts/2024-08-16-Optional.md
> +---
수정 완료했습니다!

2024-09-06 07:03 UTC, chan99k approved these changes
고생하셨습니다 ~ 🥇

2024-09-06 07:03 UTC, merged