feat: 20240902_브라우저_보안_정책_김민규
Kernel360/blog pull request #82
Opened 2024-09-09 16:10 UTC by kimminkyeu

20240902 기술세미나 기술블로그 PR입니다.
감사합니다

2024-09-10 03:23 UTC, chan99k requested changes
블로그 서식 지정을 위한 텍스트 작성을 부탁드립니다.

2024-09-10 03:23 UTC, chan99k commented on 기술세미나/_posts/2024-09-02-browser-security.md
> +# 브라우저 보안 정책
최상단 부분에 이미지처럼 서식을 지정하는 텍스트가 필요합니다.

![image](https://github.com/user-attachments/assets/204cea7f-8714-493b-94fc-c4878e3d2d2d)

2024-09-10 03:23 UTC, chan99k commented on 기술세미나/_posts/2024-09-02-browser-security.md
> +# 브라우저 보안 정책
백틱 ` 은 포함하시면 안돼요

2024-09-11 07:48 UTC, kimminkyeu commented on 기술세미나/_posts/2024-09-02-browser-security.md
> +# 브라우저 보안 정책
@chan99k 넵 반영했습니다~!

2024-09-11 08:41 UTC, chan99k approved these changes
민규님 고생하셨습니다-!!

2024-09-11 08:41 UTC, merged