feat: 20241010_FSD_도입_가이드_이재용
Kernel360/blog pull request #93
Opened 2024-10-11 04:45 UTC by enigsuss

2024-10-11 07:10 UTC, chan99k reviewed
시험 RQ 입니다

2024-10-11 07:11 UTC, chan99k requested changes
시험 RQ 입니다

2024-10-11 07:11 UTC, chan99k approved these changes

2024-10-15 14:57 UTC, tonyfromundefined reviewed
전반적으로 FSD에 대한 소개에 가깝다고 느꼈는데요. 장점으로 나열된 것들이 저에게는 큰 공감으로 와닿지는 않았어요. 재용님이 경험적으로 느끼신 장점이나 사례들을 첨부해야 좀 더 근거가 탄탄한 좋은 글이 될거같아요~

2024-10-21 05:55 UTC, merged